spring.application.name=spring_security_keycloack
server.port=8090

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/spring-keycloack-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/spring-keycloack-app/protocol/openid-connect/certs

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG